"""Model Registry Security module.

Provides ModelRecord, source tracking, checksum calculation and verification,
provenance scoring, MBOM generation, and simple persistence hooks.
"""

from .models import ModelRecord
from .tracker import SourceTracker
from .checksum import calculate_sha256, verify_model
from .evidence_origin import (
    EVIDENCE_ORIGIN_VERSION,
    EvidenceOrigin,
    FactLedger,
    ORIGIN_TRUST_WEIGHT,
    coerce_origin,
    is_verified_grade,
    ledger_from_list,
    origin_trust_weight,
    tag_fact,
)
from .provenance_v2 import (
    PROVENANCE_SCORING_VERSION,
    assess_provenance_v2,
    determine_provenance_risk,
)
from .mbom import generate_mbom
from .mbom_v2 import AI_BOM_SPEC_VERSION, generate_ai_bom_v2, verify_ai_bom_v2
from .dependency_discovery import discover_dependencies, merge_dependencies
from .dependency_discovery_v2 import (
    DEPENDENCY_DISCOVERY_SCORING_VERSION,
    discover_dependencies_v2,
)
from .artifact_integrity_v2 import (
    ARTIFACT_INTEGRITY_SCORING_VERSION,
    measure_artifact_integrity_v2,
    verify_artifact_integrity_v2,
)
from .attestation import create_provenance_attestation, verify_provenance_attestation
from .attestation_v2 import (
    PROVENANCE_ATTESTATION_SCHEMA_VERSION,
    create_provenance_attestation_v2,
    verify_provenance_attestation_v2,
)
from .advisories import normalize_advisory
from .advisory_matcher_v2 import (
    ADVISORY_MATCHER_SCORING_VERSION,
    match_dependency_advisories_v2,
)
from .advisory_feed import create_advisory_feed, verify_advisory_feed
from .advisory_feed_v2 import (
    ADVISORY_FEED_V2_SCHEMA_VERSION,
    create_advisory_feed_v2,
    verify_advisory_feed_v2,
)
from .serialization_scanner import (
    SCAN_VERSION as SERIALIZATION_SCAN_VERSION,
    STATUS_CLEAN,
    STATUS_UNSAFE,
    STATUS_NO_FILE,
    STATUS_UNSUPPORTED,
    STATUS_ERROR,
    scan_file as scan_model_artifact,
)
from .hf_model_card import (
    HF_MODEL_CARD_VERSION,
    parse_snapshot_dir,
    fetch_from_hub,
    enrich_ledger,
)
from .sigstore_verifier import (
    SIGSTORE_VERIFIER_VERSION,
    verify_file as verify_sigstore,
    find_bundle,
)
from .cyclonedx_bom import (
    CYCLONEDX_SPEC_VERSION,
    export_bom,
    import_bom,
)
from .weight_inspector import (
    INSPECTOR_VERSION as WEIGHT_INSPECTOR_VERSION,
    STATUS_INSPECTED as WEIGHT_STATUS_INSPECTED,
    STATUS_NO_FILE as WEIGHT_STATUS_NO_FILE,
    STATUS_UNSUPPORTED as WEIGHT_STATUS_UNSUPPORTED,
    STATUS_ERROR as WEIGHT_STATUS_ERROR,
    STATUS_HEADER_ONLY as WEIGHT_STATUS_HEADER_ONLY,
    inspect_file as inspect_model_weights,
)
from .lineage_graph import (
    LINEAGE_VERSION,
    derive_lineage,
)
from .fact_reconciler import (
    RECONCILER_VERSION,
    DECIDABILITY_BOUNDS,
    reconcile as reconcile_facts,
)
from .mcp_scanner import (
    SCAN_VERSION as MCP_SCAN_VERSION,
    STATUS_CLEAN as MCP_STATUS_CLEAN,
    STATUS_SUSPICIOUS as MCP_STATUS_SUSPICIOUS,
    STATUS_UNSAFE as MCP_STATUS_UNSAFE,
    STATUS_CHANGED as MCP_STATUS_CHANGED,
    STATUS_NO_TOOLS as MCP_STATUS_NO_TOOLS,
    scan_tool_descriptor,
    scan_server_tools,
)
from .agent_registry import (
    REGISTRY_VERSION as AGENT_REGISTRY_VERSION,
    AgentRegistryError,
    STATUS_ACTIVE as AGENT_STATUS_ACTIVE,
    STATUS_SUSPENDED as AGENT_STATUS_SUSPENDED,
    STATUS_QUARANTINED as AGENT_STATUS_QUARANTINED,
    STATUS_DEREGISTERED as AGENT_STATUS_DEREGISTERED,
    TRUST_VERIFIED as AGENT_TRUST_VERIFIED,
    TRUST_INTERNAL as AGENT_TRUST_INTERNAL,
    TRUST_EXTERNAL as AGENT_TRUST_EXTERNAL,
    TRUST_USER as AGENT_TRUST_USER,
    TRUST_UNTRUSTED as AGENT_TRUST_UNTRUSTED,
    CAPABILITY_FLAGS,
    CAPABILITY_RISK_RANK,
    register_agent,
    get_agent,
    list_agents,
    deregister_agent,
    set_agent_status,
    set_tool_block,
    link_manifest as link_agent_manifest,
)
from .tool_manifest import (
    MANIFEST_VERSION as TOOL_MANIFEST_VERSION,
    ManifestError,
    create_manifest as create_tool_manifest,
    verify_manifest as verify_tool_manifest,
    register_manifest as register_tool_manifest,
    get_manifest as get_tool_manifest,
    list_manifests as list_tool_manifests,
)
from .rag_inventory import (
    INVENTORY_VERSION as RAG_INVENTORY_VERSION,
    RAGInventoryError,
    ACCESS_CONTROL_MODES,
    TRUST_VERIFIED,
    TRUST_INTERNAL,
    TRUST_EXTERNAL,
    TRUST_USER_GENERATED,
    TRUST_UNTRUSTED,
    TRUST_LABELS,
    TRUST_RANK,
    register_store as register_rag_store,
    get_vector_store,
    list_vector_stores,
    register_document as register_rag_document,
    get_document as get_rag_document,
    list_documents as list_rag_documents,
)
from .ai_threat_intel import (
    THREAT_INTEL_VERSION,
    SOURCE_OWASP_LLM, SOURCE_MITRE_ATLAS, SOURCE_OWASP_AGENTIC, SOURCE_CUSTOM,
    SEVERITY_CRITICAL as THREAT_SEV_CRITICAL,
    SEVERITY_HIGH as THREAT_SEV_HIGH,
    SEVERITY_MEDIUM as THREAT_SEV_MEDIUM,
    SEVERITY_LOW as THREAT_SEV_LOW,
    CATEGORY_PROMPT_ATTACKS, CATEGORY_DATA_ATTACKS, CATEGORY_SUPPLY_CHAIN,
    CATEGORY_EXFILTRATION, CATEGORY_AVAILABILITY, CATEGORY_MODEL_INTEGRITY,
    CATEGORY_IDENTITY_ATTACKS,
    ThreatIntelError,
    ingest_threat, get_threat, list_threats,
    correlate_model, correlate_agent, correlate_tool,
    build_threat_landscape,
)
from .nhi_registry import (
    NHI_VERSION,
    NHI_MODEL_SERVING, NHI_AGENT_WORKER, NHI_TOOL_EXECUTOR,
    NHI_PIPELINE_RUNNER, NHI_DATA_CONNECTOR, NHI_GATEWAY,
    NHI_TYPES,
    NHI_PENDING, NHI_ACTIVE, NHI_DORMANT, NHI_DEPROVISIONING, NHI_REVOKED,
    NHI_STATES,
    HYGIENE_CLEAN, HYGIENE_REVIEW_NEEDED, HYGIENE_AT_RISK, HYGIENE_CRITICAL,
    NHIError,
    register_nhi, get_nhi, list_nhis,
    update_nhi_state, update_nhi,
    assess_nhi_hygiene,
)
from .identity_registry import (
    IDENTITY_VERSION,
    PRINCIPAL_MODEL, PRINCIPAL_AGENT, PRINCIPAL_TOOL,
    PRINCIPAL_DATASET, PRINCIPAL_HUMAN, PRINCIPAL_SERVICE,
    PRINCIPAL_TYPES,
    TRUST_UNTRUSTED as IDENTITY_TRUST_UNTRUSTED,
    TRUST_EXTERNAL as IDENTITY_TRUST_EXTERNAL,
    TRUST_INTERNAL as IDENTITY_TRUST_INTERNAL,
    TRUST_PRIVILEGED as IDENTITY_TRUST_PRIVILEGED,
    TRUST_LEVELS as IDENTITY_TRUST_LEVELS,
    DELEGATION_ACTIVE, DELEGATION_REVOKED, DELEGATION_EXPIRED,
    IdentityError,
    register_principal, get_principal, list_principals, update_principal,
    grant_delegation, get_delegation, revoke_delegation, list_delegations,
    verify_authority, get_authority_chain,
)
from .skill_scanner import (
    SKILL_SCANNER_VERSION,
    STATUS_CLEAN as SKILL_STATUS_CLEAN,
    STATUS_SUSPICIOUS as SKILL_STATUS_SUSPICIOUS,
    STATUS_UNSAFE as SKILL_STATUS_UNSAFE,
    STATUS_ERROR as SKILL_STATUS_ERROR,
    RISK_PERMISSION_SCOPE_CREEP, RISK_UNSIGNED_PUBLISHER,
    RISK_SUSPICIOUS_DEPENDENCY, RISK_OBFUSCATED_ENTRY_POINT,
    RISK_COVERT_NETWORK_ACCESS, RISK_COVERT_CODE_EXECUTION,
    RISK_CAPABILITY_MISMATCH, RISK_INJECTION_PATTERN,
    RISK_CATEGORIES as SKILL_RISK_CATEGORIES,
    scan_skill_manifest,
    scan_skill_registry,
)

__all__ = [
    "ModelRecord",
    "SourceTracker",
    "calculate_sha256",
    "verify_model",
    "EVIDENCE_ORIGIN_VERSION",
    "EvidenceOrigin",
    "FactLedger",
    "ORIGIN_TRUST_WEIGHT",
    "coerce_origin",
    "is_verified_grade",
    "ledger_from_list",
    "origin_trust_weight",
    "tag_fact",
    "PROVENANCE_SCORING_VERSION",
    "assess_provenance_v2",
    "determine_provenance_risk",
    "generate_mbom",
    "AI_BOM_SPEC_VERSION",
    "generate_ai_bom_v2",
    "verify_ai_bom_v2",
    "discover_dependencies",
    "merge_dependencies",
    "DEPENDENCY_DISCOVERY_SCORING_VERSION",
    "discover_dependencies_v2",
    "ARTIFACT_INTEGRITY_SCORING_VERSION",
    "measure_artifact_integrity_v2",
    "verify_artifact_integrity_v2",
    "create_provenance_attestation",
    "verify_provenance_attestation",
    "PROVENANCE_ATTESTATION_SCHEMA_VERSION",
    "create_provenance_attestation_v2",
    "verify_provenance_attestation_v2",
    "normalize_advisory",
    "ADVISORY_MATCHER_SCORING_VERSION",
    "match_dependency_advisories_v2",
    "create_advisory_feed",
    "verify_advisory_feed",
    "ADVISORY_FEED_V2_SCHEMA_VERSION",
    "create_advisory_feed_v2",
    "verify_advisory_feed_v2",
    "SERIALIZATION_SCAN_VERSION",
    "STATUS_CLEAN",
    "STATUS_UNSAFE",
    "STATUS_NO_FILE",
    "STATUS_UNSUPPORTED",
    "STATUS_ERROR",
    "scan_model_artifact",
    # Phase 3 — HuggingFace model card
    "HF_MODEL_CARD_VERSION",
    "parse_snapshot_dir",
    "fetch_from_hub",
    "enrich_ledger",
    # Phase 3 — Sigstore verifier
    "SIGSTORE_VERIFIER_VERSION",
    "verify_sigstore",
    "find_bundle",
    # Phase 3 — CycloneDX BOM
    "CYCLONEDX_SPEC_VERSION",
    "export_bom",
    "import_bom",
    # Phase 5 — Weight inspector
    "WEIGHT_INSPECTOR_VERSION",
    "WEIGHT_STATUS_INSPECTED",
    "WEIGHT_STATUS_NO_FILE",
    "WEIGHT_STATUS_UNSUPPORTED",
    "WEIGHT_STATUS_ERROR",
    "WEIGHT_STATUS_HEADER_ONLY",
    "inspect_model_weights",
    # Phase 5 — Lineage graph
    "LINEAGE_VERSION",
    "derive_lineage",
    # Phase 5 — Fact reconciler
    "RECONCILER_VERSION",
    "DECIDABILITY_BOUNDS",
    "reconcile_facts",
    # Phase 6 — MCP tool supply-chain scanner
    "MCP_SCAN_VERSION",
    "MCP_STATUS_CLEAN",
    "MCP_STATUS_SUSPICIOUS",
    "MCP_STATUS_UNSAFE",
    "MCP_STATUS_CHANGED",
    "MCP_STATUS_NO_TOOLS",
    "scan_tool_descriptor",
    "scan_server_tools",
    # Phase C — Agent registry
    "AGENT_REGISTRY_VERSION",
    "AgentRegistryError",
    "AGENT_STATUS_ACTIVE",
    "AGENT_STATUS_SUSPENDED",
    "AGENT_STATUS_QUARANTINED",
    "AGENT_STATUS_DEREGISTERED",
    "AGENT_TRUST_VERIFIED",
    "AGENT_TRUST_INTERNAL",
    "AGENT_TRUST_EXTERNAL",
    "AGENT_TRUST_USER",
    "AGENT_TRUST_UNTRUSTED",
    "CAPABILITY_FLAGS",
    "CAPABILITY_RISK_RANK",
    "register_agent",
    "get_agent",
    "list_agents",
    "deregister_agent",
    "set_agent_status",
    "set_tool_block",
    "link_agent_manifest",
    # Phase C — Signed tool manifests
    "TOOL_MANIFEST_VERSION",
    "ManifestError",
    "create_tool_manifest",
    "verify_tool_manifest",
    "register_tool_manifest",
    "get_tool_manifest",
    "list_tool_manifests",
    # Phase B — RAG vector-store inventory
    "RAG_INVENTORY_VERSION",
    "RAGInventoryError",
    "ACCESS_CONTROL_MODES",
    "TRUST_VERIFIED",
    "TRUST_INTERNAL",
    "TRUST_EXTERNAL",
    "TRUST_USER_GENERATED",
    "TRUST_UNTRUSTED",
    "TRUST_LABELS",
    "TRUST_RANK",
    "register_rag_store",
    "get_vector_store",
    "list_vector_stores",
    "register_rag_document",
    "get_rag_document",
    "list_rag_documents",
    # Feature 1 — AI-native threat intelligence engine
    "THREAT_INTEL_VERSION",
    "SOURCE_OWASP_LLM", "SOURCE_MITRE_ATLAS", "SOURCE_OWASP_AGENTIC", "SOURCE_CUSTOM",
    "THREAT_SEV_CRITICAL", "THREAT_SEV_HIGH", "THREAT_SEV_MEDIUM", "THREAT_SEV_LOW",
    "CATEGORY_PROMPT_ATTACKS", "CATEGORY_DATA_ATTACKS", "CATEGORY_SUPPLY_CHAIN",
    "CATEGORY_EXFILTRATION", "CATEGORY_AVAILABILITY", "CATEGORY_MODEL_INTEGRITY",
    "CATEGORY_IDENTITY_ATTACKS",
    "ThreatIntelError",
    "ingest_threat", "get_threat", "list_threats",
    "correlate_model", "correlate_agent", "correlate_tool",
    "build_threat_landscape",
    # Feature F3 — Non-human identity (NHI) lifecycle governance
    "NHI_VERSION",
    "NHI_MODEL_SERVING", "NHI_AGENT_WORKER", "NHI_TOOL_EXECUTOR",
    "NHI_PIPELINE_RUNNER", "NHI_DATA_CONNECTOR", "NHI_GATEWAY",
    "NHI_TYPES",
    "NHI_PENDING", "NHI_ACTIVE", "NHI_DORMANT", "NHI_DEPROVISIONING", "NHI_REVOKED",
    "NHI_STATES",
    "HYGIENE_CLEAN", "HYGIENE_REVIEW_NEEDED", "HYGIENE_AT_RISK", "HYGIENE_CRITICAL",
    "NHIError",
    "register_nhi", "get_nhi", "list_nhis",
    "update_nhi_state", "update_nhi",
    "assess_nhi_hygiene",
    # Phase G — Skill / plugin supply-chain scanner
    "SKILL_SCANNER_VERSION",
    "SKILL_STATUS_CLEAN", "SKILL_STATUS_SUSPICIOUS", "SKILL_STATUS_UNSAFE", "SKILL_STATUS_ERROR",
    "RISK_PERMISSION_SCOPE_CREEP", "RISK_UNSIGNED_PUBLISHER",
    "RISK_SUSPICIOUS_DEPENDENCY", "RISK_OBFUSCATED_ENTRY_POINT",
    "RISK_COVERT_NETWORK_ACCESS", "RISK_COVERT_CODE_EXECUTION",
    "RISK_CAPABILITY_MISMATCH", "RISK_INJECTION_PATTERN",
    "SKILL_RISK_CATEGORIES",
    "scan_skill_manifest",
    "scan_skill_registry",
    # Feature 3 — Model/agent identity and delegation registry
    "IDENTITY_VERSION",
    "PRINCIPAL_MODEL", "PRINCIPAL_AGENT", "PRINCIPAL_TOOL",
    "PRINCIPAL_DATASET", "PRINCIPAL_HUMAN", "PRINCIPAL_SERVICE",
    "PRINCIPAL_TYPES",
    "IDENTITY_TRUST_UNTRUSTED", "IDENTITY_TRUST_EXTERNAL",
    "IDENTITY_TRUST_INTERNAL", "IDENTITY_TRUST_PRIVILEGED",
    "IDENTITY_TRUST_LEVELS",
    "DELEGATION_ACTIVE", "DELEGATION_REVOKED", "DELEGATION_EXPIRED",
    "IdentityError",
    "register_principal", "get_principal", "list_principals", "update_principal",
    "grant_delegation", "get_delegation", "revoke_delegation", "list_delegations",
    "verify_authority", "get_authority_chain",
]
